mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.senjyouhara.seata.demo  # 注意：对应实体类的路径
  configuration:
    mapUnderscoreToCamelCase: true
